python3 ../cnn_2D.py s01 valence without_base
python3 ../cnn_2D.py s02 valence without_base
python3 ../cnn_2D.py s03 valence without_base
python3 ../cnn_2D.py s04 valence without_base
python3 ../cnn_2D.py s05 valence without_base
python3 ../cnn_2D.py s06 valence without_base
python3 ../cnn_2D.py s07 valence without_base
python3 ../cnn_2D.py s08 valence without_base
python3 ../cnn_2D.py s09 valence without_base
python3 ../cnn_2D.py s10 valence without_base
python3 ../cnn_2D.py s11 valence without_base
python3 ../cnn_2D.py s12 valence without_base
python3 ../cnn_2D.py s13 valence without_base
python3 ../cnn_2D.py s14 valence without_base
python3 ../cnn_2D.py s15 valence without_base
python3 ../cnn_2D.py s16 valence without_base
python3 ../cnn_2D.py s17 valence without_base
python3 ../cnn_2D.py s18 valence without_base
python3 ../cnn_2D.py s19 valence without_base
python3 ../cnn_2D.py s20 valence without_base
python3 ../cnn_2D.py s21 valence without_base
python3 ../cnn_2D.py s22 valence without_base
python3 ../cnn_2D.py s23 valence without_base
python3 ../cnn_2D.py s24 valence without_base
python3 ../cnn_2D.py s25 valence without_base
python3 ../cnn_2D.py s26 valence without_base
python3 ../cnn_2D.py s27 valence without_base
python3 ../cnn_2D.py s28 valence without_base
python3 ../cnn_2D.py s29 valence without_base
python3 ../cnn_2D.py s30 valence without_base
python3 ../cnn_2D.py s31 valence without_base
python3 ../cnn_2D.py s32 valence without_base
