python3 ../cnn_2D.py s01 valence with_base
python3 ../cnn_2D.py s02 valence with_base
python3 ../cnn_2D.py s03 valence with_base
python3 ../cnn_2D.py s04 valence with_base
python3 ../cnn_2D.py s05 valence with_base
python3 ../cnn_2D.py s06 valence with_base
python3 ../cnn_2D.py s07 valence with_base
python3 ../cnn_2D.py s08 valence with_base
python3 ../cnn_2D.py s09 valence with_base
python3 ../cnn_2D.py s10 valence with_base
python3 ../cnn_2D.py s11 valence with_base
python3 ../cnn_2D.py s12 valence with_base
python3 ../cnn_2D.py s13 valence with_base
python3 ../cnn_2D.py s14 valence with_base
python3 ../cnn_2D.py s15 valence with_base
python3 ../cnn_2D.py s16 valence with_base
python3 ../cnn_2D.py s17 valence with_base
python3 ../cnn_2D.py s18 valence with_base
python3 ../cnn_2D.py s19 valence with_base
python3 ../cnn_2D.py s20 valence with_base
python3 ../cnn_2D.py s21 valence with_base
python3 ../cnn_2D.py s22 valence with_base
python3 ../cnn_2D.py s23 valence with_base
python3 ../cnn_2D.py s24 valence with_base
python3 ../cnn_2D.py s25 valence with_base
python3 ../cnn_2D.py s26 valence with_base
python3 ../cnn_2D.py s27 valence with_base
python3 ../cnn_2D.py s28 valence with_base
python3 ../cnn_2D.py s29 valence with_base
python3 ../cnn_2D.py s30 valence with_base
python3 ../cnn_2D.py s31 valence with_base
python3 ../cnn_2D.py s32 valence with_base
