python3 ../cnn_2D.py s01 arousal with_base
python3 ../cnn_2D.py s02 arousal with_base
python3 ../cnn_2D.py s03 arousal with_base
python3 ../cnn_2D.py s04 arousal with_base
python3 ../cnn_2D.py s05 arousal with_base
python3 ../cnn_2D.py s06 arousal with_base
python3 ../cnn_2D.py s07 arousal with_base
python3 ../cnn_2D.py s08 arousal with_base
python3 ../cnn_2D.py s09 arousal with_base
python3 ../cnn_2D.py s10 arousal with_base
python3 ../cnn_2D.py s11 arousal with_base
python3 ../cnn_2D.py s12 arousal with_base
python3 ../cnn_2D.py s13 arousal with_base
python3 ../cnn_2D.py s14 arousal with_base
python3 ../cnn_2D.py s15 arousal with_base
python3 ../cnn_2D.py s16 arousal with_base
python3 ../cnn_2D.py s17 arousal with_base
python3 ../cnn_2D.py s18 arousal with_base
python3 ../cnn_2D.py s19 arousal with_base
python3 ../cnn_2D.py s20 arousal with_base
python3 ../cnn_2D.py s21 arousal with_base
python3 ../cnn_2D.py s22 arousal with_base
python3 ../cnn_2D.py s23 arousal with_base
python3 ../cnn_2D.py s24 arousal with_base
python3 ../cnn_2D.py s25 arousal with_base
python3 ../cnn_2D.py s26 arousal with_base
python3 ../cnn_2D.py s27 arousal with_base
python3 ../cnn_2D.py s28 arousal with_base
python3 ../cnn_2D.py s29 arousal with_base
python3 ../cnn_2D.py s30 arousal with_base
python3 ../cnn_2D.py s31 arousal with_base
python3 ../cnn_2D.py s32 arousal with_base
