python3 ../cnn_2D.py s01 arousal without_base
python3 ../cnn_2D.py s02 arousal without_base
python3 ../cnn_2D.py s03 arousal without_base
python3 ../cnn_2D.py s04 arousal without_base
python3 ../cnn_2D.py s05 arousal without_base
python3 ../cnn_2D.py s06 arousal without_base
python3 ../cnn_2D.py s07 arousal without_base
python3 ../cnn_2D.py s08 arousal without_base
python3 ../cnn_2D.py s09 arousal without_base
python3 ../cnn_2D.py s10 arousal without_base
python3 ../cnn_2D.py s11 arousal without_base
python3 ../cnn_2D.py s12 arousal without_base
python3 ../cnn_2D.py s13 arousal without_base
python3 ../cnn_2D.py s14 arousal without_base
python3 ../cnn_2D.py s15 arousal without_base
python3 ../cnn_2D.py s16 arousal without_base
python3 ../cnn_2D.py s17 arousal without_base
python3 ../cnn_2D.py s18 arousal without_base
python3 ../cnn_2D.py s19 arousal without_base
python3 ../cnn_2D.py s20 arousal without_base
python3 ../cnn_2D.py s21 arousal without_base
python3 ../cnn_2D.py s22 arousal without_base
python3 ../cnn_2D.py s23 arousal without_base
python3 ../cnn_2D.py s24 arousal without_base
python3 ../cnn_2D.py s25 arousal without_base
python3 ../cnn_2D.py s26 arousal without_base
python3 ../cnn_2D.py s27 arousal without_base
python3 ../cnn_2D.py s28 arousal without_base
python3 ../cnn_2D.py s29 arousal without_base
python3 ../cnn_2D.py s30 arousal without_base
python3 ../cnn_2D.py s31 arousal without_base
python3 ../cnn_2D.py s32 arousal without_base
